name: dataforge
description: A Dart code generator that forges data classes with JSON serialization support from annotated classes.
version: 0.2.1
homepage: https://github.com/your_username/dataforge
repository: https://github.com/your_username/dataforge
issue_tracker: https://github.com/your_username/dataforge/issues
documentation: https://github.com/your_username/dataforge#readme

executables:
  dataforge:

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  analyzer: ^8.0.0
  collection: ^1.17.0
  path: ^1.7.0
  args: ^2.7.0
  dataforge_annotation:
    path: ./annotation

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.15