name: dataforge_annotation
description: Annotations for dataforge package to generate data classes with JSON serialization support.
version: 0.2.1
homepage: https://github.com/your_username/dataforge
repository: https://github.com/your_username/dataforge
issue_tracker: https://github.com/your_username/dataforge/issues
documentation: https://github.com/your_username/dataforge#readme

environment:
  sdk: ^3.0.0